"""new fields added

Revision ID: aa02e0aad2ba
Revises: 3c165d818b63
Create Date: 2018-11-30 11:49:06.354252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa02e0aad2ba'
down_revision = '3c165d818b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('dc', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'dc')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
